export const INITIAL_BOARD = [
  [
    { type: "r", player: 'b', id: "br1" },
    { type: "n", player: 'b', id: "bn1" },
    { type: "b", player: 'b', id: "bb1" },
    { type: "q", player: 'b', id: "bq0" },
    { type: "k", player: 'b', id: "bk0" },
    { type: "b", player: 'b', id: "bb2" },
    { type: "n", player: 'b', id: "bn2" },
    { type: "r", player: 'b', id: "br2" },
  ],
  [
    { type: "p", player: 'b', id: "bp1" },
    { type: "p", player: 'b', id: "bp2" },
    { type: "p", player: 'b', id: "bp3" },
    { type: "p", player: 'b', id: "bp4" },
    { type: "p", player: 'b', id: "bp5" },
    { type: "p", player: 'b', id: "bp6" },
    { type: "p", player: 'b', id: "bp7" },
    { type: "p", player: 'b', id: "bp8" },
  ],
  [null, null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null, null],
  [
    { type: "p", player: 'w', id: "bp1" },
    { type: "p", player: 'w', id: "bp2" },
    { type: "p", player: 'w', id: "bp3" },
    { type: "p", player: 'w', id: "bp4" },
    { type: "p", player: 'w', id: "bp5" },
    { type: "p", player: 'w', id: "bp6" },
    { type: "p", player: 'w', id: "bp7" },
    { type: "p", player: 'w', id: "bp8" },
  ],
  [
    { type: "r", player: 'w', id: "br1" },
    { type: "n", player: 'w', id: "bn1" },
    { type: "b", player: 'w', id: "bb1" },
    { type: "q", player: 'w', id: "bq0" },
    { type: "k", player: 'w', id: "bk0" },
    { type: "b", player: 'w', id: "bb2" },
    { type: "n", player: 'w', id: "bn2" },
    { type: "r", player: 'w', id: "br2" },
  ],
]
