export const INITIAL_BOARD = [
  [
    { type: "r", player: 1 },
    { type: "n", player: 1 },
    { type: "b", player: 1 },
    { type: "q", player: 1 },
    { type: "k", player: 1 },
    { type: "b", player: 1 },
    { type: "n", player: 1 },
    { type: "r", player: 1 },
  ],
  [
    { type: "p", player: 1 },
    { type: "p", player: 1 },
    { type: "p", player: 1 },
    { type: "p", player: 1 },
    { type: "p", player: 1 },
    { type: "p", player: 1 },
    { type: "p", player: 1 },
    { type: "p", player: 1 },
  ],
  [null, null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null, null],
  [
    { type: "p", player: 0 },
    { type: "p", player: 0 },
    { type: "p", player: 0 },
    { type: "p", player: 0 },
    { type: "p", player: 0 },
    { type: "p", player: 0 },
    { type: "p", player: 0 },
    { type: "p", player: 0 },
  ],
  [
    { type: "r", player: 0 },
    { type: "n", player: 0 },
    { type: "b", player: 0 },
    { type: "q", player: 0 },
    { type: "k", player: 0 },
    { type: "b", player: 0 },
    { type: "n", player: 0 },
    { type: "r", player: 0 },
  ],
]
